name: BigDoorsDungeons
version: '${project.version}'
main: it.novaverse.bigdoorsdungeons.BigDoorsDungeons
api-version: '1.20'
load: STARTUP
depend:
  - MythicDungeons
  - BigDoors
softdepend:
  - PlaceholderAPI
